site_name: Virtual Channel SDK for Citrix Receiver for Chrome 2.6
site_description: Documentation for the Virtual Channel SDK for Citrix Receiver for Chrome 2.6
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
     anchorlink: true

pages:
 - Introduction: index.md
 - What's new: whats-new.md
 - System requirements: system-requirements.md
 - Using example programs: using-example-programs.md
 - Building examples: building-examples.md
 - Programming guide: programming-guide.md
 - Programming reference: programming-reference.md
 - Classes:
   - CustomVC: customvc.md
   - ReceiverError: receiver-error.md
   - Utils: utils.md
 - Namespaces:
   - receiver: namespace-receiver.md
 - Global: global.md
